# Generated by Django 5.2.12 on 2026-04-26 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('danger_count', models.IntegerField(default=0)),
                ('normal_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('look_back', models.IntegerField(default=90)),
                ('threshold', models.FloatField(default=88.3794)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(blank=True, null=True)),
                ('curah_hujan_mm', models.FloatField(default=0.0)),
                ('cuaca_kode', models.FloatField(default=0.0)),
                ('smd_kanan_q_ls', models.FloatField(default=0.0)),
                ('smd_kiri_q_ls', models.FloatField(default=0.0)),
                ('tma_lag1', models.FloatField(default=0.0)),
                ('tma_lag2', models.FloatField(default=0.0)),
                ('tma_lag3', models.FloatField(default=0.0)),
                ('delta_tma', models.FloatField(default=0.0)),
                ('tma_rolling_mean_3', models.FloatField(default=0.0)),
                ('jam_kode', models.FloatField(default=0.0)),
                ('tma_predicted', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('threshold_used', models.FloatField(default=88.3794)),
                ('source', models.CharField(default='Manual', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='dashboard.batchsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
